Models/Fornecedor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FornecedoresEmpresa.Models
{
    public class Fornecedor : Pessoa
    {
        public virtual ISet<TelefoneFornecedor> Telefones { get; set; }

        public virtual Empresa Empresa { get; set; }
    }
}

Models/TelefoneFornecedor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FornecedoresEmpresa.Models
{
    public class TelefoneFornecedor
    {
        public virtual int Id { get; set; }

        public virtual string Numero { get; set; }

        public virtual Fornecedor Fornecedor { get; set; }
    }
}

Controllers/FornecedorController.cs
using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using NHibernate;
using FornecedoresEmpresa.Data.Persistencia;
using FornecedoresEmpresa.ViewModel;
using FornecedoresEmpresa.Models;
using FornecedoresEmpresa.Regras;
using FornecedoresEmpresa.Utils;
using System.Linq;

namespace FornecedoresEmpresa.Controllers
{
    public class FornecedorController : Controller
    {
        private readonly ISession Sessao;

        public FornecedorController(ISession sessao)
        {
            this.Sessao = sessao;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var listaFornecedor = await new FornecedorDados(Sessao).ListarTodos();

            var model = new FornecedorViewModelIndex();

            model.ListaFornecedor = listaFornecedor;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Filtrar(FornecedorViewModelIndex model)
        {
            var listaFornecedor = await new FornecedorDados(Sessao).BuscarTodos(model.Fornecedor);

            model.ListaFornecedor = listaFornecedor;

            return View("Index", model);
        }

        [HttpGet]
        public IActionResult Cadastrar()
        {
            var model = new FornecedorViewModelCadastro();
            model.ListaTelefoneFornecedor.Add(new TelefoneFornecedorPartialViewModel());

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Cadastrar(FornecedorViewModelCadastro model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var setTelefoneFornecedor = new TelefoneFornecedorRegras(Sessao)
                                        .CriaTelefoneFornecedores(model.ListaTelefoneFornecedor);

            var fornecedor = new Fornecedor()
            {
                Nome = model.Nome,
                Cpf = model.Cpf,
                Cnpj = model.Cnpj,
                Rg = model.Rg,
                DataNascimento = model.DataNascimento,
                Telefones = setTelefoneFornecedor
            };

            try
            {
                await new FornecedorRegras(Sessao).CadastrarAsync(fornecedor);

                TempData["Mensagem"] = "Fornecedor cadastrado com sucesso!";

                return RedirectToAction("Index");
            }
            catch (UsuarioException uex)
            {
                TempData["Mensagem"] = uex.Message;
            }
            catch (Exception ex)
            {
                TempData["Mensagem"] = "Erro Interno: " + ex.Message;
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Alterar(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var fornecedor = await new FornecedorDados(Sessao).BuscarPorId((int)id);

            if (fornecedor == null)
            {
                TempData["Mensagem"] = "Fornecedor não encontrado";
                return RedirectToAction("Index");
            }

            var listaModelTelefone = new List<TelefoneFornecedorPartialViewModel>();

            foreach (var telefone in fornecedor.Telefones)
            {
                listaModelTelefone.Add(new TelefoneFornecedorPartialViewModel()
                {
                    Numero = telefone.Numero,
                    Id = telefone.Id
                });
            }

            var model = new FornecedorViewModelAlterar()
            {
                Id = fornecedor.Id,
                Cnpj = fornecedor.Cnpj,
                Cpf = fornecedor.Cpf,
                DataNascimento = fornecedor.DataNascimento,
                Nome = fornecedor.Nome,
                Rg = fornecedor.Rg,
                ListaTelefoneFornecedor = listaModelTelefone,
                TipoPessoa = fornecedor.Cpf == null ? "PJ" : "PF"
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Alterar(FornecedorViewModelAlterar model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                var fornecedor = await new FornecedorDados(Sessao).BuscarPorId(model.Id);

                if (fornecedor == null)
                {
                    TempData["Mensagem"] = "Fornecedor não encontrado";
                    return RedirectToAction("Index");
                }

                var telefoneFornecedorRegras = new TelefoneFornecedorRegras(Sessao);

                var setTelefoneFornecedor = telefoneFornecedorRegras.CriaTelefoneFornecedores(model.ListaTelefoneFornecedor);
                await telefoneFornecedorRegras.ExcluiTelefonesFornecedorAsync(fornecedor.Telefones, setTelefoneFornecedor);

                fornecedor.Nome = model.Nome;
                fornecedor.Rg = model.Rg;
                fornecedor.Cpf = model.Cpf;
                fornecedor.Cnpj = model.Cnpj;
                fornecedor.DataNascimento = model.DataNascimento;
                fornecedor.Telefones = setTelefoneFornecedor;

                await new FornecedorRegras(Sessao).AlterarAsync(fornecedor);

                TempData["Mensagem"] = "Fornecedor salvo com sucesso!";

                return RedirectToAction("Index");
            }
            catch (UsuarioException uex)
            {
                TempData["Mensagem"] = uex.Message;
            }
            catch (Exception ex)
            {
                TempData["Mensagem"] = "Erro Interno: " + ex.Message;
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Excluir(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var fornecedorDados = new FornecedorDados(Sessao);
            var fornecedor = await fornecedorDados.BuscarPorId((int)id);

            if (fornecedor == null)
            {
                return RedirectToAction("Index");
            }

            try
            {
                await fornecedorDados.Excluir(fornecedor);

                TempData["Mensagem"] = "Fornecedor excluído com sucesso!";
            }
            catch (Exception ex)
            {
                TempData["Mensagem"] = "Erro " + ex.Message;
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> RemoverAssociacao(int? id)
        {
            if (!id.HasValue)
            {
                return RedirectToAction("Index", "Empresa");
            }

            try
            {
                await new FornecedorRegras(Sessao).RemoverAssociacaoComEmpresaAsync((int)id);

                TempData["Mensagem"] = "Fornecedor desassociado com sucesso!";
            }
            catch (UsuarioException uex)
            {
                TempData["Mensagem"] = uex.Message;
            }
            catch (Exception ex)
            {
                TempData["Mensagem"] = "Erro " + ex.Message;
            }

            var url = HttpContext.Request.Headers["Referer"];

            return Redirect(url);
        }

        public ViewResult AdicionarTelefone(int indice, string nomeLista, string divId)
        {
            var model = new TelefoneFornecedorPartialViewModel()
            {
                DivId = divId,
                NomeLista = nomeLista,
                Indice = indice
            };

            return View("_TelefoneFornecedor", model);
        }
    }
}

Views/Fornecedor/Alterar.cshtml
@model FornecedoresEmpresa.ViewModel.FornecedorViewModelAlterar

@{
    ViewData["Title"] = "Alterar Fornecedor";
    var nomeLista = nameof(Model.ListaTelefoneFornecedor);
    var contadorTelefone = 0;
    var prefixoDivId = "telefone";
}

@section scripts
{
    <script async src="~/js/fornecedor.js"></script>
    <script>
        $(document).ready(function () {
            escondeBotoes();

            $("#adicionarTelefone").on("click", function (event) {
                event.preventDefault();
                let nomeLista = "@nomeLista";
                let indice = $(".telefones").length;
                let divId = "@prefixoDivId" + indice;

                ajaxAdicionaTelefone(this.href, nomeLista, indice, divId);
            });

        });

        function escondeBotoes() {
            let i = 1;
            let indice = $(".telefones").length;
            while (i < indice - 1) {
                $(`#remover-telefone${i}`).hide();
                i++;
            }
        }
        
    </script>
}

<div class="row">
    <div class="col mb-3">
        <h2>Alterar Fornecedor</h2>
    </div>
</div>

@using (Html.BeginForm("Alterar", "Fornecedor", FormMethod.Post))
{
    <div class="form-group row">
        @Html.HiddenFor(m => m.TipoPessoa)
        @Html.LabelFor(m => m.TipoPessoa, new { @class = "col-form-label col-lg-2" })
        <div class="col-lg-3 col-4">
            @Html.DropDownListFor(m => m.TipoPessoa, Model.ListaTipoPessoa, new { @class = "form-control", id = "selectTipoPessoa", required = "true", disabled = "true" })
        </div>
    </div>

    <div id="itensFormulario" class="d-none">
        <div class="form-group row">
            @Html.LabelFor(m => m.Nome, new { @class = "col-form-label col-lg-2" })

            <div class="col-lg-5 col-10">
                @Html.EditorFor(m => m.Nome, new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(m => m.Nome)
            </div>
        </div>

        <div class="form-group row pessoa-fisica">
            @Html.LabelFor(m => m.Cpf, new { @class = "col-form-label col-lg-2" })

            <div class="col-sm-4 col-3">
                @Html.EditorFor(m => m.Cpf, new { htmlAttributes = new { @class = "form-control", type = "number" } })

                @Html.ValidationMessageFor(m => m.Cpf)
            </div>
        </div>

        <div class="form-group row pessoa-fisica">
            @Html.LabelFor(m => m.Rg, new { @class = "col-form-label col-lg-2" })

            <div class="col-sm-4 col-3">
                @Html.EditorFor(m => m.Rg, new { htmlAttributes = new { @class = "form-control", type = "number" } })

                @Html.ValidationMessageFor(m => m.Rg)
            </div>
        </div>

        <div class="form-group row pessoa-juridica">
            @Html.LabelFor(m => m.Cnpj, new { @class = "col-form-label col-lg-2" })

            <div class="col-sm-4 col-3">
                @Html.EditorFor(m => m.Cnpj, new { htmlAttributes = new { @class = "form-control", type = "number" } })

                @Html.ValidationMessageFor(m => m.Cnpj)
            </div>
        </div>

        <div class="form-group row pessoa-fisica">
            @Html.LabelFor(m => m.DataNascimento, new { @class = "col-form-label col-lg-2" })

            <div class="col-lg-3 col-4">
                @Html.EditorFor(m => m.DataNascimento, new { htmlAttributes = new { type = "date", @class = "form-control" } })

                @Html.ValidationMessageFor(m => m.DataNascimento)
            </div>
        </div>

        <div class="form-group row">
            <div class="col-2 mt-5">
                <a class="btn btn-sm btn-success" href="@Url.ActionLink("AdicionarTelefone")" id="adicionarTelefone">+ Número</a>
            </div>

            <div class="col-lg-3 col-4 mt-5" id="telefonesDiv">
                @foreach (var telefone in Model.ListaTelefoneFornecedor)
                {
                    telefone.NomeLista = nomeLista;
                    telefone.Indice = contadorTelefone;
                    telefone.DivId = prefixoDivId + contadorTelefone;

                    {
                        await Html.RenderPartialAsync("_TelefoneFornecedor", telefone);
                    }

                    contadorTelefone++;
                }
            </div>
        </div>

        <div class="form-group row">
            <div class="col mt-4">
                <button class="btn btn-success" type="submit">Salvar</button>
            </div>
        </div>

    </div>
}

<div class="form-group row">
    <div class="col">
        <a class="btn btn-sm btn-secondary" href="@Url.ActionLink("Index")">Voltar</a>
    </div>
</div>

Views/Fornecedor/Cadastrar.cshtml
@model FornecedoresEmpresa.ViewModel.FornecedorViewModelCadastro

@{
    ViewData["Title"] = "Cadastrar Fornecedor";
    var nomeLista = nameof(Model.ListaTelefoneFornecedor);
    var contadorTelefone = 0;
    var prefixoDivId = "telefone";
}

@section scripts
{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
    <script async src="~/js/fornecedor.js"></script>
    <script>
        $(document).ready(function () {

            $("#adicionarTelefone").on("click", function (event) {
                event.preventDefault();
                let nomeLista = "@nomeLista";
                let indice = $(".telefones").length;
                let divId = "@prefixoDivId" + indice;

                ajaxAdicionaTelefone(this.href, nomeLista, indice, divId);
            });

        });
    </script>
}

<div class="row">
    <div class="col mb-3">
        <h2>Cadastrar Fornecedor</h2>
    </div>
</div>

@using (Html.BeginForm("Cadastrar", "Fornecedor", FormMethod.Post))
{
    <div class="form-group row">
        @Html.LabelFor(m => m.TipoPessoa, new { @class = "col-form-label col-lg-2" })
        <div class="col-lg-3 col-4">
            @Html.DropDownListFor(m => m.TipoPessoa, Model.ListaTipoPessoa, "Selecione uma Opção", new { @class = "form-control", id = "selectTipoPessoa", required = "true" })
        </div>
    </div>

    <div id="itensFormulario" class="d-none">
        <div class="form-group row">
            @Html.LabelFor(m => m.Nome, new { @class = "col-form-label col-lg-2" })

            <div class="col-lg-5 col-10">
                @Html.EditorFor(m => m.Nome, new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(m => m.Nome)
            </div>
        </div>

        <div class="form-group row pessoa-fisica">
            @Html.LabelFor(m => m.Cpf, new { @class = "col-form-label col-lg-2" })

            <div class="col-sm-4 col-3">
                @Html.EditorFor(m => m.Cpf, new { htmlAttributes = new { @class = "form-control", type = "number" } })

                @Html.ValidationMessageFor(m => m.Cpf)
            </div>
        </div>

        <div class="form-group row pessoa-fisica">
            @Html.LabelFor(m => m.Rg, new { @class = "col-form-label col-lg-2" })

            <div class="col-sm-4 col-3">
                @Html.EditorFor(m => m.Rg, new { htmlAttributes = new { @class = "form-control", type = "number" } })

                @Html.ValidationMessageFor(m => m.Rg)
            </div>
        </div>

        <div class="form-group row pessoa-juridica">
            @Html.LabelFor(m => m.Cnpj, new { @class = "col-form-label col-lg-2" })

            <div class="col-sm-4 col-3">
                @Html.EditorFor(m => m.Cnpj, new { htmlAttributes = new { @class = "form-control", type = "number" } })

                @Html.ValidationMessageFor(m => m.Cnpj)
            </div>
        </div>

        <div class="form-group row pessoa-fisica">
            @Html.LabelFor(m => m.DataNascimento, new { @class = "col-form-label col-lg-2" })

            <div class="col-lg-3 col-4">
                @Html.EditorFor(m => m.DataNascimento, new { htmlAttributes = new { type = "date", @class = "form-control" } })

                @Html.ValidationMessageFor(m => m.DataNascimento)
            </div>
        </div>

        <div class="form-group row">
            <div class="col-2 mt-5">
                <a class="btn btn-sm btn-success" href="@Url.ActionLink("AdicionarTelefone")" id="adicionarTelefone">+ Número</a>
            </div>

            <div class="col-lg-3 col-4 mt-5" id="telefonesDiv">
                @foreach (var telefone in Model.ListaTelefoneFornecedor)
                {
                    telefone.NomeLista = nomeLista;
                    telefone.Indice = contadorTelefone;
                    telefone.DivId = prefixoDivId + contadorTelefone;

                    {
                        await Html.RenderPartialAsync("_TelefoneFornecedor", telefone);
                    }

                    contadorTelefone++;
                }
            </div>
        </div>

        <div class="form-group row">
            <div class="col mt-4">
                <button class="btn btn-success" type="submit">Cadastrar</button>
            </div>
        </div>

    </div>
}

<div class="form-group row">
    <div class="col">
        <a class="btn btn-sm btn-secondary" href="@Url.ActionLink("Index")">Voltar</a>
    </div>
</div>

Views/Fornecedor/Index.cshtml
@model FornecedoresEmpresa.ViewModel.FornecedorViewModelIndex

@{
    ViewData["Title"] = "Fornecedores";
}

@section scripts
{
    <script>
        $(document).ready(function () {
            $('#modalExcluir').on('shown.bs.modal', function (event) {
                let idFornecedor = event.relatedTarget.dataset.id;
                let href = "@Url.Action("Excluir","Fornecedor")/" + idFornecedor;
                $(this).find("#btnExcluir").attr("href", href);
            });
        });
    </script>
}

<div class="row">
    <div class="col">
        <a class="btn btn-success" href="@Url.ActionLink("Cadastrar")"> Novo Fornecedor </a>
    </div>
</div>

@using (Html.BeginForm("Filtrar", "Fornecedor", FormMethod.Post))
{
<div class="form-row">
    <div class="col-auto">
        @Html.LabelFor(m => m.Fornecedor.Nome, new { @class = "sr-only" })
        @Html.EditorFor(m => m.Fornecedor.Nome, new { htmlAttributes = new { @class = "form-control my-2 mt-5", placeholder = "Nome" } })
    </div>

    <div class="col-auto">
        <label for="@nameof(Model.Fornecedor.Cpf)" class="sr-only">CPF</label>
        @Html.EditorFor(m => m.Fornecedor.Cpf, new { htmlAttributes = new { @class = "form-control my-2 mt-5", placeholder = "CPF" } })
    </div>

    <div class="col-auto">
        <label for="@nameof(Model.Fornecedor.Cnpj)" class="sr-only">CNPJ</label>
        @Html.EditorFor(m => m.Fornecedor.Cnpj, new { htmlAttributes = new { @class = "form-control my-2 mt-5", placeholder = "CNPJ" } })
    </div>

    <div class="col-auto mt-3">
        <label for="@nameof(Model.Fornecedor.DataCadastro)">Data de Cadastro</label>
        @Html.EditorFor(m => m.Fornecedor.DataCadastro, new { htmlAttributes = new { type = "date", @class = "form-control" } })
    </div>

    <div class="col-auto mt-5">
        <input type="submit" value="Filtrar" class="btn btn-success" />
        <a href="@Url.Action("Index")" class="btn btn-primary">Resetar</a>
    </div>
</div>
}

<main class="table-responsive">
    <table class="table table-striped table-dark">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Tipo Pessoa</th>
                <th>CNPJ/CPF</th>
                <th>RG</th>
                <th>Data de Nascimento</th>
                <th>Telefones</th>
                <th>Data de Cadastro</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var fornecedor in Model.ListaFornecedor)
            {
                <tr>
                    <td>@fornecedor.Nome</td>
                    <td>@(fornecedor.Cnpj == null ? "Pessoa Física" : "Pessoa Jurídica")</td>
                    <td>@(fornecedor.Cnpj == null ? fornecedor.Cpf : fornecedor.Cnpj)</td>
                    <td>@fornecedor.Rg</td>
                    <td>@(fornecedor.DataNascimento.HasValue ? fornecedor.DataNascimento.Value.ToShortDateString() : "")</td>
                    <td>
                        @foreach (var telefone in fornecedor.Telefones)
                        {
                            @(telefone.Numero) <br>
                        }
                    </td>
                    <td>@fornecedor.DataCadastro.ToShortDateString()</td>
                    <td>
                        @Html.ActionLink("Alterar", "Alterar", new { id = fornecedor.Id }, new { @class = "btn btn-sm btn-secondary" })
                        <button type="button" data-toggle="modal" data-target="#modalExcluir" data-id="@fornecedor.Id" class="btn btn-sm btn-danger">Excluir</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</main>

<div class="modal" id="modalExcluir" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Excluir Fornecedor</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Quer realmente excluir esse Fornecedor?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                <a href="#" id="btnExcluir" class="btn btn-danger">Excluir</a>
            </div>
        </div>
    </div>
</div>

Views/Fornecedor/_TelefoneFornecedor.cshtml
@model FornecedoresEmpresa.ViewModel.TelefoneFornecedorPartialViewModel

@{
    var name = Model.NomeLista + "[" + Model.Indice + "].";
    var nameNumero = name + nameof(Model.Numero);
    var nameId = name + nameof(Model.Id);
    Layout = "";
}
<div id="@Model.DivId" class="mb-3">
    @Html.Hidden((string)nameId, Model.Id)
    @Html.LabelFor(m => m.Numero, new { @class = "sr-only" })

    @Html.EditorFor(m => m.Numero, "name", (string)nameNumero, new { htmlAttributes = new { @class = "form-control telefones", placeholder = "Número de Telefone", type = "number" } })

    @Html.ValidationMessageFor(m => m.Numero, null, new { @data_valmsg_for = (string)nameNumero })

    <button type="button" id="remover-@Model.DivId" class="btnRemover btn btn-sm btn-danger float-right mt-3" aria-label="Close">
        Remover
    </button>
</div>